### PR TITLE
Treat .cc files same way as .cpp

### PR DESCRIPTION
**Pull request by davidgfnet**

### CODE REVIEW

**Comment by WinterMute** [comment]
Why though?

**Comment by davidgfnet** [comment]
There's projects and libraries that use .cc as C++ file extension, this
makes it way easier to build them. Otherwise I need to either hack my rules
file or add some extra rules in the Makefile.
Thanks!

**Comment by fincs** [comment]
If what you're doing is porting projects and libraries to the Switch (or other console we support), you should stick to the project's original build system and not try replacing it with a devkitPro-style makefile.

**Comment by davidgfnet** [comment]
It's a mixture really, some projects have both kinds of files due to embedding a small library sometimes.
Perhaps there's a more general way to write this rule so that we don't have to duplicate the rule for both cc and cpp? Is that your concern?

**Comment by fincs** [comment]
No. I'm saying that if there is a project that already has a build system, you shouldn't try replacing it with a devkitPro-style makefile. Use the original build system.

**Pull request closed without merging**
